# Make file - Runs a certain command based on the script being run

.PHONY: tests

install:
	@echo soon

clean:
	@find . -name \*.pyc -delete

reset:
	@python reset-database.py

tests:
	@python tests/*.py

stat:
	@python getDatabase.py

fingerprint-songs: clean
	@python fingerprintSongs.py

recognize-listen: clean
	@python recognize-from-microphone.py -s $(seconds)

recognize-file: clean
	@python recognize-from-file.py